name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm type:check
      - run: pnpm test
      - run: pnpm build:production
      - name: pack
        run: pnpm pack
      - uses: actions/upload-artifact@v7
        with:
          name: freelens-gpu-extension-tgz
          path: "*.tgz"
          if-no-files-found: error
